apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: authors
spec:
  adminAuth: 
    secretName: basic-auth
  clusterName: infinispan 
  name: authors
  template: |
    <infinispan>
      <cache-container>
        <distributed-cache name="authors" mode="SYNC">
          <encoding media-type="application/x-protostream"/>
          <persistence>
            <file-store/>
          </persistence>
        </distributed-cache>
      </cache-container>
    </infinispan>
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: statistics
spec:
  adminAuth: 
    secretName: basic-auth
  clusterName: infinispan 
  name: statistics
  template: |
    <infinispan>
      <cache-container>
        <distributed-cache name="statistics" mode="SYNC">
          <encoding media-type="application/x-protostream"/>
          <persistence>
            <file-store/>
          </persistence>
        </distributed-cache>
      </cache-container>
    </infinispan>
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: since-id
spec:
  adminAuth: 
    secretName: basic-auth
  clusterName: infinispan 
  name: since-id
  template: |
    <infinispan>
      <cache-container>
        <distributed-cache name="since-id" mode="SYNC">
          <encoding media-type="application/x-protostream"/>
          <persistence>
            <file-store/>
          </persistence>
        </distributed-cache>
      </cache-container>
    </infinispan>
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: last-gp
spec:
  adminAuth: 
    secretName: basic-auth
  clusterName: infinispan 
  name: last-gp
  template: |
    <infinispan>
      <cache-container>
        <distributed-cache name="last-gp" mode="SYNC">
          <encoding media-type="application/x-protostream"/>
          <persistence>
            <file-store/>
          </persistence>
        </distributed-cache>
      </cache-container>
    </infinispan>